version:                   "3.3"

services:
  yetiforce-mysql:
    image:                 mysql:5
    ports:
      - "3306:3306"
    volumes:
      - yetiforce-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: yetiforce
      MYSQL_DATABASE:      yetiforce
      MYSQL_USER:          yetiforce
      MYSQL_PASSWORD:      yetiforce

  yetiforce:
    image:                 f4bio/yetiforcecrm:4.4.0
    ports:
      - "12380:80"
      - "12443:443"
    depends_on:
      - yetiforce-mysql
    volumes:
      - yetiforce-data:/var/www/html

volumes:
  yetiforce-data:
  yetiforce-mysql-data:
